sudo: required

language: csharp
mono: none
dist: xenial
dotnet: 3.1

script:
  - dotnet restore
  - dotnet build
  - dotnet test

before_install:
  - openssl aes-256-cbc -K $encrypted_5c63586ad085_key -iv $encrypted_5c63586ad085_iv
    -in TestSettings.json.enc -out SpecflowAPITests/TestSettings.json -d
